In [1]:
import pandas as pd
ted = pd.read_csv('ted_main.csv')
transcripts = pd.read_csv('transcripts.csv')
ted.head()

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

In [2]:
df = ted.merge(transcripts, on='url')
df.head()

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views,transcript
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110,Good morning. How are you?(Laughter)It's been ...
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520,"Thank you so much, Chris. And it's truly a gre..."
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550,If you're here today — and I'm very happy that...
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869,"About 10 years ago, I took on the task to teac..."

In [3]:
df = df[['title', 'description', 'main_speaker', 'tags', 'transcript', 'views']]

In [4]:
df['description'] = df['description'].fillna('')
df['transcript'] = df['transcript'].fillna('')
df['tags'] = df['tags'].fillna('')

In [5]:
import ast

def clean_tags(text):
    try:
        return " ".join(ast.literal_eval(text))
    except:
        return ""

df['tags'] = df['tags'].apply(clean_tags)

In [6]:
df['content'] = (
    df['description'] + " " +
    df['transcript'] + " " +
    df['tags'] + " " +
    df['main_speaker']
)

In [7]:
print(ted.shape)
print(transcripts.shape)

(2550, 17)
(2467, 2)

In [8]:
print(df.shape)
df.head()

(2467, 7)

,title,description,main_speaker,tags,transcript,views,content
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,Ken Robinson,children creativity culture dance education pa...,Good morning. How are you?(Laughter)It's been ...,47227110,Sir Ken Robinson makes an entertaining and pro...
1,Averting the climate crisis,With the same humor and humanity he exuded in ...,Al Gore,alternative energy cars climate change culture...,"Thank you so much, Chris. And it's truly a gre...",3200520,With the same humor and humanity he exuded in ...
2,Simplicity sells,New York Times columnist David Pogue takes aim...,David Pogue,computers entertainment interface design media...,"(Music: ""The Sound of Silence,"" Simon & Garfun...",1636292,New York Times columnist David Pogue takes aim...
3,Greening the ghetto,"In an emotionally charged talk, MacArthur-winn...",Majora Carter,MacArthur grant activism business cities envir...,If you're here today — and I'm very happy that...,1697550,"In an emotionally charged talk, MacArthur-winn..."
4,The best stats you've ever seen,You've never seen data presented like this. Wi...,Hans Rosling,Africa Asia Google demo economics global devel...,"About 10 years ago, I took on the task to teac...",12005869,You've never seen data presented like this. Wi...

In [10]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [12]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [13]:
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]
    
    return " ".join(words)

In [14]:
df['content'] = df['content'].apply(preprocess)

In [15]:
df['content'][0][:300]

'sir ken robinson make entertaining profoundly moving case creating education system nurture rather undermines creativity good morning youlaughterits great hasnt ive blown away whole thing fact im leavinglaughterthere three theme running conference relevant want talk one extraordinary evidence human '

In [16]:
df = df.reset_index(drop=True)
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=40000, ngram_range=(1,2))
tfidf_matrix = tfidf.fit_transform(df['content'])
print(tfidf_matrix.shape)

(2467, 40000)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_talk(title, top_n=5):
    
    if title not in indices:
        return ["Talk not found"]
    
    idx = indices[title]
    
    similarity = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    
    weighted_score = (
        0.8 * similarity +
        0.2 * (df['views'] / df['views'].max())
    )
    
    similar_idx = weighted_score.argsort()[::-1][1:top_n+1]
    
    return df['title'].iloc[similar_idx].values

In [19]:
recommend_talk("Do schools kill creativity?", 5)

array(['Your body language may shape who you are',
       "How to escape education's death valley",
       'Bring on the learning revolution!', 'The power of vulnerability',
       'Why we do what we do'], dtype=object)

In [22]:
def recommend_talk(title, top_n=5):
    
    if title not in indices:
        return ["Talk not found"]
    
    idx = indices[title]
    
    similarity = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    
    weighted_score = (
        0.8 * similarity +
        0.2 * (df['views'] / df['views'].max())
    )
    
    similar_idx = weighted_score.argsort()[::-1][1:top_n*2]  # take more initially
    
    results = df[['title','main_speaker','views']].iloc[similar_idx]
    
    results = results.drop_duplicates(subset='title')  # REMOVE DUPLICATES
    
    return results.head(top_n)

In [23]:
recommend_talk("The power of vulnerability", 5)

                                         title  main_speaker     views
1112                        Listening to shame   Brené Brown   7988894
0                  Do schools kill creativity?  Ken Robinson  47227110
1268  Your body language may shape who you are     Amy Cuddy  43155405
5                         Why we do what we do  Tony Robbins  20685401
649           How great leaders inspire action   Simon Sinek  34309432

In [24]:
import pickle

pickle.dump(tfidf, open('tfidf.pkl','wb'))
pickle.dump(tfidf_matrix, open('matrix.pkl','wb'))
pickle.dump(indices, open('indices.pkl','wb'))
df.to_pickle('data.pkl')

In [25]:
recommend_talk("Do schools kill creativity?", 5)

                                         title  main_speaker     views
1268  Your body language may shape who you are     Amy Cuddy  43155405
1421    How to escape education's death valley  Ken Robinson   6657858
663          Bring on the learning revolution!  Ken Robinson   7266316
800                 The power of vulnerability   Brené Brown  31168150
5                         Why we do what we do  Tony Robbins  20685401

In [26]:
print("TED Talk Recommendation System Completed Successfully")

TED Talk Recommendation System Completed Successfully